routes/web.php
<?php

Auth::routes();

Route::middleware(['auth',])->group(function () {

    Route::resource('backup', 'backupController');
    Route::resource('products','admin\ProductsController');
    Route::resource('waiters','admin\WaitersController');
    Route::resource('tables','admin\TablesController');
    Route::resource('customers','admin\CustomersController');
    Route::resource('dashboard','admin\WorksOrdersController');
    Route::resource('services','admin\ServicesController');
    Route::resource('configuration','admin\ConfigurationController');
    Route::resource('user', 'UserController');
    Route::resource('logins', 'LoginController');
    Route::resource('permission', 'PermissionController');
    Route::get('/', 'admin\WorksOrdersController@index')->name('home');
    Route::get('reports', 'ReportsController@index');
    Route::get('getAllDataTable', 'admin\WorksOrdersController@getAllDataTable');
    Route::get('data', 'admin\WorksOrdersController@getDataReport');
    Route::get('about','admin\AboutController@index');
    Route::get('dataRange', 'admin\WorksOrdersController@ReportDateRange');
    Route::get('generationCode', 'admin\WorksOrdersController@generationCode');
    Route::get('getActiveTables','admin\TablesController@getActiveTables');
    Route::get('getProducts','admin\ProductsController@indexGet');
    Route::get('getWaiters','admin\WaitersController@indexGet');
    Route::get('getTables','admin\TablesController@indexGet');
    Route::get('getCustomers','admin\CustomersController@indexGet');
    Route::get('actionCustomer/{code}','admin\CustomersController@codeCustomer');
    Route::get('nameCustomer/{name}','admin\CustomersController@nameCustomer');
    Route::get('getBackup', 'backupController@indexGet');
    Route::get('facture/{id}','admin\ConfigurationController@getTableDataFacture');
    Route::get('getTableData/{id}','admin\WorksOrdersController@getTableData');
    Route::post('moveWorkOrder', 'admin\WorksOrdersController@moveWorkOrder');
    Route::put('getStatusWorkOrder/{id}','admin\WorksOrdersController@getWorkOrderStatus');
    Route::put('changeCode/{code}','admin\WorksOrdersController@changeCode');
    Route::delete('deleteWorkOrder/{id}','admin\WorksOrdersController@delete');

});
  

Route::get('refresh_captcha', 'Auth\LoginController@refreshCaptcha')->name('refresh_captcha');  
Route::get('reset', 'AnswerController@showAnswerRequestForm')->name('password.request');
Route::Post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/resets', 'Auth\ResetPasswordController@reset')->name('password.resets');
Route::get('response', 'AnswerController@index');
Route::get('verification', 'AnswerController@verificationAnswer');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPasswordNotification;
use Nicolaslopezj\Searchable\SearchableTrait;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SearchableTrait;


    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'last_name', 'question', 'answer', 'email', 'password', 'status'
    ];

    protected $hidden = [];

    protected $appends = ['full_name'];


    protected $searchable = [
        'columns' => [
          'users.name' => 5,
          'users.last_name' => 5,
        ]
    ];


    /*
    |
    | ** Relationships model **
    |
    */

    public function logins()
    {
        return $this->hasMany('App\Models\Login');
    }

    /*
    |
    | ** Accesors model **
    |
    */

    public function getEncodeIDAttribute()
    {
        return \Hashids::encode($this->id);
    }

    public function getFullNameAttribute()
    {
        return title_case($this->name).' '. title_case($this->last_name);
    }

    public function getDisplayNameAttribute()
    {
        $name      = explode(' ', $this->name);
        $last_name = explode(' ', $this->last_name);

        return title_case($name[0]).' '.title_case($last_name[0]);
    }

    public function getDisplayStatusAttribute()
    {
        return $this->status == 1 ? 'Activo' : 'Denegado';
    }

    /*
    |
    | ** Mutators model **
    |
    */
    public function setAnswerAttribute($attribute)
    {
        if (!empty($attribute))
        {
           $this->attributes['answer'] = strlen($attribute) < 60 ? bcrypt($attribute) : $attribute;
        }
    }

    public function setPasswordAttribute($attribute)
    {
        if (!empty($attribute))
        {
           $this->attributes['password'] = strlen($attribute) < 60 ? bcrypt($attribute) : $attribute;
        }
    }

    /*
    |
    | ** Send the custom password reset notification **
    |
    */

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

}

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ env('APP_NAME') }} - @yield('title')</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="{{ asset('css/buttons.dataTables.min.css') }}" rel="stylesheet" type="text/css">
    @push('scripts')
    <script src="{{ asset('jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/js/dataTables.buttons.js') }}"></script>
    <script src="{{ asset('js/js/jszip.min.js') }}"></script>
    <script src="{{ asset('js/js/pdfmake.min.js') }}"></script>
    <script src="{{ asset('js/js/buttons.html5.js') }}"></script>
    <script src="{{ asset('js/js/buttons.print.js') }}"></script>
    <script src="{{ asset('js/js/buttons.bootstrap.js') }}"></script> 
    <script src="{{ asset('js/js/vfs_fonts.js') }}"></script> 
    
    @endpush
    <meta name="robots" content="noindex, nofollow">
    </style>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @stack('styles')
    <style type="text/css">

    
    @font-face {
      font-family: 'Source';
      src: url(/fonts/vendor/source-sans-pro/SourceSansPro-Regular.ttf);
    }
    body
    {
      font-family: 'Source' !important;
    }
    }
    .btn-primary
    {
      /*background-color: rgba(1, 60, 163, 255);*/
      background-color : rgba(0, 0, 0, 255);
    }
    .main-sidebar
    {
        background:rgba(0, 0, 0, 255);
    }
    </style>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">
        <a href="{{ url('/') }}" class="logo" style="background-color : rgba(0,0, 0, 255);">
          <span class="logo-mini"><b>S</b>B</span>
          <span class="logo-lg"><b>SIS</b>BAR</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" style="background-color : rgba(0,0, 0, 255);" role="navigation">
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
                  <span class="fa fa fa-user"></span>
                  <span class="hidden-xs">{{ Auth::user()->display_name }}</span>
                </a>
                <ul class="dropdown-menu" >
                  <li class="user-header" style="background-color : rgba(0, 0, 10, 255);">
                    <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->
                    <i class="fa fa-user fa-5x" style="color:#fff;"></i>
                    <p>
                      {{ Auth::user()->display_name }}
                      <br>
                      {{ Auth::user()->hasrole('admin') ? 'Administrador' : 'Usuario' }}
                      <small>Miembro desde {{ Auth::user()->created_at->format('d-m-Y') }}</small>
                    </p>
                  </li>
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{{ url('user', [Auth::user()->encode_id]) }}" class="btn btn-default btn-flat">
                        <i class="fa fa-eye"></i> Datos
                      </a>
                    </div>
                    <div class="pull-right">
                      <a href="logout" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">
                        <i class="fa fa-sign-out"></i> Salir
                      </a>
                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                      </form>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <!-- Uncomment this line to activate the control right sidebar button
              <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li>
              -->
            </ul>
          </div>
        </nav>
      </header>

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar" style="background-color: black;">
        @include('layouts.partials.leftmenu')
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <section class="content-header">
          <h1>
            @yield('page_title')
            <small>@yield('page_subtitle')</small>
          </h1>
          <ol class="breadcrumb">
            @section('breadcrumb')
            @show
          </ol>
        </section>

        <!-- Main content -->
        <section class="content container-fluid">
          <!--Page Content Here -->
          @yield('content')
        </section>
      </div>

      <!-- confirm modal -->
      @include('layouts.partials.confirm_modal')
      @include('layouts.partials.confirm_modal_dashboard')
      @include('layouts.partials.confirm_modal_product')
      @include('layouts.partials.confirm_modal_table')
      @include('layouts.partials.confirm_modal_product_edit')
      @include('layouts.partials.confirm_modal_backup')
      @include('layouts.partials.confirm_modal_backup_delete')

      <!-- modal to alert of backup -->
      @include('layouts.partials.apply_backup_modal')
      @include('layouts.partials.facture')


      <!-- Main Footer
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
        </div>
      </footer>
       -->
      <!-- Control Sidebar -->
      <!-- Uncomment this line to activate the control right sidebar menu
      @@include('layouts.partials.sidebar')
      -->
    </div>

    <!-- REQUIRED JS SCRIPTS -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript">
      if ( localStorage.getItem('side_bar_state') == "0" ){
        $('.sidebar-toggle').data('run_from_code', '1');
        //$('.sidebar-toggle').trigger('click');
      }
      else{
        $('.sidebar-toggle').data('run_from_code', '0');
        $('.sidebar-toggle').trigger('click');
      }

      $('.sidebar-toggle').bind('click', function (){
        if ( !localStorage.getItem('side_bar_state') || ( $('.sidebar-toggle').data('run_from_code') == '1' && localStorage.getItem('side_bar_state') == '0' ) ){
          localStorage.setItem('side_bar_state', '1');
        }
        else{
          localStorage.setItem('side_bar_state', '0');
        }
      });
      console.log()
    </script>
    @stack('scripts')
  </body>
</html>

resources/views/layouts/adminfront.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ env('APP_NAME') }} - @yield('title')</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="robots" content="noindex, nofollow">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @stack('styles')
  </head>

  <body class="hold-transition login-page">
    <!--Page Content Here -->
    @yield('content')

    <!-- REQUIRED JS SCRIPTS -->
    <script src="{{ asset('js/app.js') }}"></script>
    @stack('scripts')
  </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>