routes/web.php
<?php

Auth::routes();

Route::middleware(['auth',])->group(function () {

    Route::resource('backup', 'backupController');
    Route::resource('products','admin\ProductsController');
    Route::resource('waiters','admin\WaitersController');
    Route::resource('tables','admin\TablesController');
    Route::resource('customers','admin\CustomersController');
    Route::resource('dashboard','admin\WorksOrdersController');
    Route::resource('services','admin\ServicesController');
    Route::resource('configuration','admin\ConfigurationController');
    Route::resource('user', 'UserController');
    Route::resource('logins', 'LoginController');
    Route::resource('permission', 'PermissionController');
    Route::get('/', 'admin\WorksOrdersController@index')->name('home');
    Route::get('reports', 'ReportsController@index');
    Route::get('getAllDataTable', 'admin\WorksOrdersController@getAllDataTable');
    Route::get('data', 'admin\WorksOrdersController@getDataReport');
    Route::get('about','admin\AboutController@index');
    Route::get('dataRange', 'admin\WorksOrdersController@ReportDateRange');
    Route::get('generationCode', 'admin\WorksOrdersController@generationCode');
    Route::get('getActiveTables','admin\TablesController@getActiveTables');
    Route::get('getProducts','admin\ProductsController@indexGet');
    Route::get('getWaiters','admin\WaitersController@indexGet');
    Route::get('getTables','admin\TablesController@indexGet');
    Route::get('getCustomers','admin\CustomersController@indexGet');
    Route::get('actionCustomer/{code}','admin\CustomersController@codeCustomer');
    Route::get('nameCustomer/{name}','admin\CustomersController@nameCustomer');
    Route::get('getBackup', 'backupController@indexGet');
    Route::get('facture/{id}','admin\ConfigurationController@getTableDataFacture');
    Route::get('getTableData/{id}','admin\WorksOrdersController@getTableData');
    Route::post('moveWorkOrder', 'admin\WorksOrdersController@moveWorkOrder');
    Route::put('getStatusWorkOrder/{id}','admin\WorksOrdersController@getWorkOrderStatus');
    Route::put('changeCode/{code}','admin\WorksOrdersController@changeCode');
    Route::delete('deleteWorkOrder/{id}','admin\WorksOrdersController@delete');

});
  

Route::get('refresh_captcha', 'Auth\LoginController@refreshCaptcha')->name('refresh_captcha');  
Route::get('reset', 'AnswerController@showAnswerRequestForm')->name('password.request');
Route::Post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/resets', 'Auth\ResetPasswordController@reset')->name('password.resets');
Route::get('response', 'AnswerController@index');
Route::get('verification', 'AnswerController@verificationAnswer');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPasswordNotification;
use Nicolaslopezj\Searchable\SearchableTrait;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SearchableTrait;


    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'last_name', 'question', 'answer', 'email', 'password', 'status'
    ];

    protected $hidden = [];

    protected $appends = ['full_name'];


    protected $searchable = [
        'columns' => [
          'users.name' => 5,
          'users.last_name' => 5,
        ]
    ];


    /*
    |
    | ** Relationships model **
    |
    */

    public function logins()
    {
        return $this->hasMany('App\Models\Login');
    }

    /*
    |
    | ** Accesors model **
    |
    */

    public function getEncodeIDAttribute()
    {
        return \Hashids::encode($this->id);
    }

    public function getFullNameAttribute()
    {
        return title_case($this->name).' '. title_case($this->last_name);
    }

    public function getDisplayNameAttribute()
    {
        $name      = explode(' ', $this->name);
        $last_name = explode(' ', $this->last_name);

        return title_case($name[0]).' '.title_case($last_name[0]);
    }

    public function getDisplayStatusAttribute()
    {
        return $this->status == 1 ? 'Activo' : 'Denegado';
    }

    /*
    |
    | ** Mutators model **
    |
    */
    public function setAnswerAttribute($attribute)
    {
        if (!empty($attribute))
        {
           $this->attributes['answer'] = strlen($attribute) < 60 ? bcrypt($attribute) : $attribute;
        }
    }

    public function setPasswordAttribute($attribute)
    {
        if (!empty($attribute))
        {
           $this->attributes['password'] = strlen($attribute) < 60 ? bcrypt($attribute) : $attribute;
        }
    }

    /*
    |
    | ** Send the custom password reset notification **
    |
    */

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreUser;
use App\Http\Requests\UpdateUser;
use App\Models\User;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:add_users')->only('store');
        $this->middleware('permission:edit_users')->only('update');
        $this->middleware('permission:delete_users')->only('destroy');
        $this->middleware('ajax', ['only' => ['store', 'update', 'destroy']]);
    }

    public function index(Request $request)
    {
        $users = User::with('roles')->with('permissions')
                       ->search($request->q)
                       ->orderBy('created_at', 'desc')
                       ->paginate(10);

        return view('admin.user.index', ['users' => $users]);
    }



    public function create()
    {
        return view('admin.user.create');
    }

    public function store(StoreUser $request)
    {
        $user = User::create($request->except('role'));

        if ($request->has('role'))
        {
            $user->assignRole($request->role);
        }

        return json_encode(['success' => true, 'user_id' => $user->encode_id]);
    }


    public function show($id)
    {
        $user = User::find(\Hashids::decode($id)[0]);

        return view('admin.user.show', ['user' => $user]);
    }


    public function edit($id)
    {
        $user = User::find(\Hashids::decode($id)[0]);

        return view('admin.user.edit', ['user' => $user]);
    }

    public function update(UpdateUser $request, $id)
    {
        $user = User::find(\Hashids::decode($id)[0]);
        $user->update($request->except('role'));

        if ($request->has('role'))
        {
            $user->syncRoles($request->role);
        }
        return json_encode(['success' => true]);
    }

    public function destroy($id)
    {
        $user = User::find(\Hashids::decode($id)[0])->delete();
        return json_encode(['success' => true]);
    }


    public function autocomplete(Request $request)
    {
        if (isset($request->q)){
            return User::search($request->q)->take(10)->get();
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('title', 'Usuarios')
@section('page_title', 'Usuarios')
@section('page_subtitle', 'Ingresar')

@section('breadcrumb')
    @parent
    <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ url('user') }}">usuarios</a></li>
    <li class="active">Ingresar</li>
@endsection

@section('content')

  <section class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="btn-group">
          @can('view_users')
          <a href="{{ url('user') }}" class="btn btn-danger"><i class="fa fa-sort-alpha-desc"></i> Listado</a>
          @endcan
          @can('add_users')
          <a href="{{ url('user/create') }}" class="btn btn-danger"><i class="fa fa-plus-square"></i> Ingresar</a>
          @endcan
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-danger">
          <form role="form" id="main-form">
            <input type="hidden" id="_url" value="{{ url('user') }}">
            <input type="hidden" id="_token" value="{{ csrf_token() }}">
            <div class="box-body">
              <div class="form-group pading">
                <label for="name">Nombres</label>
                <input class="form-control" pattern="[A-Za-z]+" title="Solo letras"  id="name" name="name" >
                <span class="missing_alert text-danger" id="name_alert"></span>
              </div>
              <div class="form-group">
                <label for="last_name">Apellidos</label>
                <input class="form-control" pattern="[A-Za-z]+" title="Solo letras" id="last_name" name="last_name" >
                <span class="missing_alert text-danger" id="last_name_alert"></span>
              </div>
          
              <div class="form-group">
                <label for="email">Correo Electrónico</label>
                <input class="form-control" id="email" name="email" >
                <span class="missing_alert text-danger" id="email_alert"></span>
              </div>
            <fieldset> 
              <div class="form-group">
                <label for="last_name">Pregunta de seguridad</label>
                <input class="form-control" id="question" name="question" >
                <span class="missing_alert text-danger" id="last_name_alert"></span>
              </div>
              
              <div class="form-group">
                <label for="last_name">Respuesta </label>
                <input class="form-control" id="answer" name="answer" >
                <span class="missing_alert text-danger" id="last_name_alert"></span>
              </div>
            </fieldset>

              <div class="form-group">
                <label for="role">Tipo de usuario</label>
                <div class="checkbox icheck">
                  <label>
                    <input type="radio" name="role" value="user" checked> Usuario&nbsp;&nbsp;
                    <input type="radio" name="role" value="admin"> Administrador
                  </label>
                </div>
              </div>
              <div class="form-group">
                
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password"  >
                <span class="missing_alert text-danger" id="password_alert"></span>
              </div>

              <div class="form-group">
                <label for="password_confirmation">Confirmar Contraseña</label>
                <input type="password" class="form-control" id="password_confirmation"    name="password_confirmation" >

                <span class="missing_alert text-danger" id="password_confirmation_alert"></span>
              </div>

              <div class="form-group">
                <label for="status">Acceso al sistema</label>
                <div class="checkbox icheck">
                  <label>
                    <input type="radio" name="status" value="1" checked> Activo&nbsp;&nbsp;
                    <input type="radio" name="status" value="0"> Deshabilitado
                  </label>
                </div>
              </div>
            </div>
            <div class="box-footer">
            <button class="btn btn-block btn-danger btn-flat submit_button" id="submit" type="submit">Guardar</button>
              <a type="submit" class="btn btn-info ajax hide" id="edit-button">
                <i class="fa fa-edit"></i> Editar
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

@endsection

@push('scripts')
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
    <script src="{{ asset('js/admin/user/create.js') }}"></script>
@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title', 'Usuarios')
@section('page_title', 'Usuarios')
@section('page_subtitle', 'Editar')

@section('breadcrumb')
    @parent
    <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ url('user') }}">usuarios</a></li>
    <li class="active">Editar</li>
@endsection

@section('content')

  <section class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="btn-group">
          @can('view_users')
          <a href="{{ url('user') }}" class="btn btn-danger"><i class="fa fa-sort-alpha-desc"></i> Listado</a>
          @endcan
          @can('add_users')
          <a href="{{ url('user/create') }}" class="btn btn-danger"><i class="fa fa-plus-square"></i> Ingresar</a>
          @endcan
          <a href="{{ url('user', [$user->encode_id]) }}" class="btn btn-danger"><i class="fa fa-eye"></i> Datos</a>
        </div>
      </div>
    </div>

    
    <br>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-danger">
          <form role="form" id="main-form">
            <input type="hidden" id="_url" value="{{ url('user', [$user->encode_id]) }}">
            <input type="hidden" id="_token" value="{{ csrf_token() }}">
            <div class="box-body">
              <div class="form-group pading">
                <label for="name">Nombres</label>
                <input class="form-control" id="name" name="name" value="{{ $user->name }}" placeholder="Nombres">
                <span class="missing_alert text-danger" id="name_alert"></span>
              </div>
              <div class="form-group">
                <label for="last_name">Apellidos</label>
                <input class="form-control" id="last_name" name="last_name" value="{{ $user->last_name }}" placeholder="Apellidos">
                <span class="missing_alert text-danger" id="last_name_alert"></span>
              </div>
              <div class="form-group">
                <label for="email">Correo Electrónico</label>
                <input class="form-control" id="email" name="email" value="{{ $user->email }}" placeholder="Correo electrónico">
                <span class="missing_alert text-danger" id="email_alert"></span>
              </div>
              @if(Auth::user()->hasrole('admin') && Auth::user()->id != $user->id)
              <div class="form-group">
                <label for="role">Tipo de usuario</label>
                <div class="checkbox icheck">
                  <label>
                    <input type="radio" name="role" value="user" {{ $user->hasRole('user') ? 'checked' : '' }}> Usuario&nbsp;&nbsp;
                    <input type="radio" name="role" value="admin" {{ $user->hasRole('admin') ? 'checked' : '' }}> Administrador
                  </label>
                </div>
              </div>
              @endif
              <div class="form-group">
                <label for="password">Nueva Contraseña</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
                <span class="missing_alert text-danger" id="password_alert"></span>
              </div>
              <div class="form-group">
                <label for="password_confirmation">Confirmar Nueva Contraseña</label>
                <input type="password"  class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Contraseña">
                <span class="missing_alert text-danger" id="password_confirmation_alert"></span>
              </div>
              @if(Auth::user()->hasrole('admin') && Auth::user()->id != $user->id)
              <div class="form-group">
                <label for="status">Acceso al sistema</label>
                <div class="checkbox icheck">
                  <label>
                    <input type="radio" name="status" value="1" {{ $user->status == 1 ? 'checked' : '' }}> Activo&nbsp;&nbsp;
                    <input type="radio" name="status" value="0" {{ $user->status == 0 ? 'checked' : '' }}> Deshabilitado&nbsp;&nbsp;
                  </label>
                </div>
              </div>
              @endif
              <br>
              <div class="form-group">
                <label for="password">Contraseña actual ({{ Auth::user()->display_name }})</label>
                <input type="password" class="form-control" id="current_password" name="current_password" placeholder="Contraseña actual">
                <span class="missing_alert text-danger" id="current_password_alert"></span>
              </div>
              <div class="box-footer">
            <button class="btn btn-block btn-danger btn-flat submit_button" id="submit" type="submit">Guardar</button>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

@endsection

@push('scripts')
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
    <script src="{{ asset('js/admin/user/edit.js') }}"></script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('title', 'Usuarios')
@section('page_title', 'Usuarios')
@section('page_subtitle', 'Listado')

@section('breadcrumb')
    @parent
    <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ url('user') }}">usuarios</a></li>
    <li class="active">Listado</li>
@endsection

@section('content')

    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group">
            @can('add_users')
            <a href="{{ url('user/create') }}" class="btn btn-danger"><i class="fa fa-plus-square"></i> Ingresar</a>

            @endcan
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Listado de usuarios</h3>
              <div class="box-tools">
              </div>
            </div>
            <div class="box-body table-responsive table-striped">
              <table class="table table-responsive table-hover">
                <tr>
                    <th>Usuario</th>
                    <th>Tipo</th>
                    <th>Correo electrónico</th>
                    <th>Acceso</th>
                    <th>Creado</th>
                    <th>Actualizado</th>
                    <th></th>
                </tr>
                @foreach ($users as $user)
                <tr class="row{{ $user->encode_id }}">
                  <td>{{ $user->full_name }}</td>
                  <td>{!! $user->hasRole('admin') ? '<b>Administrador</b>' : 'Usuario' !!}</td>
                  <td>{{ $user->email  }}</td>
                  <td><span class="badge {{ $user->status ? 'bg-green' : 'bg-red' }}">{{ $user->display_status }}</span></td>
                  <td>{{ $user->created_at }}</td>
                  <td>{{ $user->updated_at }}</td>
                  <td>
                    <div class="dropdown">
                      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                        <i class="fa fa-gears"></i> <span class="caret"></span>
                      </button>
                      <ul class=" dropdown-menu dropdown-menu-right">
                        <li><a href="{{  url('user', [$user->encode_id]) }}"><i class="fa fa-eye"></i> Perfil</a></li>
                        @can('edit_users')
                        <li><a href="{{ url('user', [$user->encode_id, 'edit']) }}"><i class="fa fa-edit"></i> Editar</a></a></li>
                        @endcan
                        @if(auth()->user()->can('delete_users') && Auth::user()->id != $user->id)
                        <li class="divider"><li>
                        <li><a href="#confirm-modal" id="{{ $user->encode_id }}"  class="del-btn" data-toggle="modal"><i class="fa fa-trash"></i> Eliminar</a></li>
                        @endif
                      </ul>
                    </div>
                  </td>
                </tr>
                @endforeach
              </table>
              <div class="box-footer clearfix">
                  {{ $users->links() }}
                  <p class="text-muted">Mostrando <strong>{{ $users->count() }}</strong> registros de <strong>{{$users->total() }}</strong> totales</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


@endsection

@push('scripts')
  <script src="{{ asset('js/admin/user/index.js') }}"></script>
@endpush

resources/views/admin/user/show.blade.php
@extends('layouts.admin')
@section('title', 'Usuarios')
@section('page_title', 'Usuarios')
@section('page_subtitle', 'Datos')
@section('breadcrumb')
    @parent
    <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ url('user') }}">usuarios</a></li>
    <li class="active">datos</li>
@endsection
@section('content')
<section class="invoice">
  <div class="row">
    <div class="col-xs-12">
      <h2 class="page-header">
        <i class="fa fa-user"></i> Datos de usuario
        <small class="pull-right">{{ $user->display_name }}</small>
      </h2>
    </div>
  </div>
  <div class="row invoice-info">
    <div class="col-sm-3 invoice-col">
      <strong>Nombre</strong><br>
        {{ $user->full_name }}
    </div>
    <div class="col-sm-3 invoice-col">
      <strong>Correo electrónico</strong>
      <br>
      {{ $user->email }}
    </div>
    <div class="col-sm-3 invoice-col">
      <strong>Estatus</strong><br>
      <span class="badge {{ $user->status ? 'bg-green' : 'bg-red' }}">{{ $user->display_status }}</span>
    </div>
    <div class="col-sm-3 invoice-col">
      <strong>Tipo de usuario</strong><br>
      {{ Auth::user()->hasrole('admin') ? 'Administrador' : 'Usuario' }}
    </div>
  </div>
  <br>
  <div class="row invoice-info">
    <div class="col-sm-3 invoice-col">
      <strong>Contraseña</strong><br>
      ********
    </div>
    <div class="col-sm-3 invoice-col">
      <strong>Creado</strong>
      <br>
      {{ $user->created_at }}
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        @can('edit_users')
        <a href="{{ url('user', [$user->encode_id, 'edit']) }}" class="btn btn-danger"><i class="fa fa-edit"></i> Editar</a>
        @endcan
      </div>
    </div>
  </div>
</section>

@endsection